management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus

  observations:
    annotations:
      enabled: true

  tracing:
    sampling:
      probability: 1.0  # 100% запросов трассируем (в проде можно 0.1 = 10%)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans  # адрес Zipkin сервера

  metrics:
    tags:
      application: virtBoot
      environment: ${ENVIRONMENT:development}
    distribution:
      # Гистограммы для HTTP запросов
      percentiles-histogram:
        http.server.requests: true
        kafka.consumer.fetch.manager.records.consumed: true
        spring.kafka.listener: true
      # SLO (Service Level Objectives)
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms, 1s, 2s
      # Перцентили
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        spring.kafka.listener: 0.5, 0.95, 0.99
    # Какие метрики включать
    enable:
      jvm: true
      tomcat: true
      kafka: true
      jdbc: true
      logback: true
      process: true
      system: true


server:
  port: 12222
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    max-connections: 10000
    mbeanregistry:
      enabled: true

spring:
  application:
    name: Bell
  threads:
    virtual:
      enabled: true
  jmx:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
    consumer:
      group-id: my-group               # ID группы потребителей
      auto-offset-reset: earliest      # Чтение сообщений с начала топика
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer    # Десериализатор ключей
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # Десериализатор значений

  datasource:
    # Настройки подключения к PostgreSQL
    url: jdbc:postgresql://localhost:5432/mydb  # URL базы данных
    username: postgres                          # Имя пользователя БД
    password: example                           # Пароль пользователя БД
    driver-class-name: org.postgresql.Driver    # Драйвер PostgreSQL

  jpa:
    # Настройки JPA и Hibernate
    hibernate:
      ddl-auto: create-drop  # Автоматическое создание/удаление таблиц при запуске/остановке
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Диалект PostgreSQL для Hibernate
    show-sql: false
    open-in-view: false

response:
  delay:
    default: 0
    session:
      create: 500
      delete: 500
      check: 0
    order:
      create: 3000
      getProducts: 1500
      getOrder: 1500

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    BellSpring: WARN

decorator:
  datasource:
    datasource-proxy:
      query:
        enable-logging: true
      slow-query:
        enable-logging: true
        threshold: 100



